NetMVCBlogApp/NetMVCBlogApp/Controllers/SeoController.cs
using NetMVCBlogApp.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Xml;

namespace NetMVCBlogApp.Controllers
{
    public class SeoController : Controller
    {
        public BlogDBEntities context { get; set; }

        public SeoController()
        {
            context = new BlogDBEntities();
        }

        [Route("sitemap.xml")]
        public ActionResult SitemapXml()
        {
            string siteUrl = Request.Url.GetLeftPart(UriPartial.Authority);
            Response.Clear();
            Response.ContentType = "text/xml";

            XmlTextWriter xmlTextWriter = new XmlTextWriter(Response.OutputStream, Encoding.UTF8);
            xmlTextWriter.WriteStartDocument();
            xmlTextWriter.WriteStartElement("urlset");
            xmlTextWriter.WriteAttributeString("xmlns", "http://www.sitemaps.org/schemas/sitemap/0.9");
            xmlTextWriter.WriteAttributeString("xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance");
            xmlTextWriter.WriteAttributeString("xsi:schemaLocation", "http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd");



            xmlTextWriter.WriteStartElement("url");
            xmlTextWriter.WriteElementString("loc", siteUrl + Url.Action("Index", "Home"));
            xmlTextWriter.WriteElementString("lastmod", DateTime.Now.ToString("yyyy-MM-dd"));
            xmlTextWriter.WriteElementString("priority", "0.5");
            xmlTextWriter.WriteElementString("changefreq", "daily");
            xmlTextWriter.WriteEndElement();

            xmlTextWriter.WriteStartElement("url");
            xmlTextWriter.WriteElementString("loc", siteUrl + Url.Action("AboutMe", "Home"));
            xmlTextWriter.WriteElementString("lastmod", DateTime.Now.AddDays(-5).ToString("yyyy-MM-dd"));
            xmlTextWriter.WriteElementString("priority", "0.5");
            xmlTextWriter.WriteElementString("changefreq", "weekly");
            xmlTextWriter.WriteEndElement();

            xmlTextWriter.WriteStartElement("url");
            xmlTextWriter.WriteElementString("loc", siteUrl + Url.Action("Contact", "Home"));
            xmlTextWriter.WriteElementString("lastmod", DateTime.Now.AddDays(-5).ToString("yyyy-MM-dd"));
            xmlTextWriter.WriteElementString("priority", "0.5");
            xmlTextWriter.WriteElementString("changefreq", "weekly");
            xmlTextWriter.WriteEndElement();



            foreach (var post in context.Post.Where(i => i.isValid).ToList())
            {
                xmlTextWriter.WriteStartElement("url");
                xmlTextWriter.WriteElementString("loc", siteUrl + "/" + post.SeoLink + "-" + post.ID);
                xmlTextWriter.WriteElementString("lastmod", post.AddedDate.ToString("yyyy-MM-dd"));
                xmlTextWriter.WriteElementString("priority", "0.5");
                xmlTextWriter.WriteElementString("changefreq", "monthly");
                xmlTextWriter.WriteEndElement();
            }

            xmlTextWriter.WriteEndDocument();

            xmlTextWriter.Flush();
            xmlTextWriter.Close();
            Response.End();

            return View();
        }

        [Route("RSS")]
        public ActionResult Rss()
        {
            string siteUrl = Request.Url.GetLeftPart(UriPartial.Authority);

            Response.Clear();
            Response.ContentType = "text/xml";

            XmlTextWriter xmlTextWriter = new XmlTextWriter(Response.OutputStream, Encoding.UTF8);
            xmlTextWriter.WriteStartDocument();
            xmlTextWriter.WriteStartElement("rss");
            xmlTextWriter.WriteAttributeString("version", "1.0");
            xmlTextWriter.WriteStartElement("channel");

            foreach (var post in context.Post.Where(i => i.isValid).ToList())
            {
                xmlTextWriter.WriteElementString("title", post.Name);
                xmlTextWriter.WriteElementString("link", siteUrl + "/" + post.SeoLink + "-" + post.ID);
                xmlTextWriter.WriteElementString("description", HttpUtility.HtmlDecode(post.Text));
                xmlTextWriter.WriteElementString("pubDate", post.AddedDate.ToString("dd.MM.yyyy"));
                xmlTextWriter.WriteElementString("language", "tr-TR");
            }

            xmlTextWriter.WriteEndDocument();

            xmlTextWriter.Flush();
            xmlTextWriter.Close();
            Response.End();

            return View();
        }

        [ChildActionOnly]
        public PartialViewResult MetaTags(string value)
        {
            Options options = context.Options.FirstOrDefault();

            if (value != null)
            {
                options.Description = value;
            }

            return PartialView(options);
        }
    }
}

NetMVCBlogApp/NetMVCBlogApp/Views/Shared/admin.cshtml
@{
    if (Session["admin"] == null)
    {
        Response.Redirect("/Account/Login");
        return;
    }

}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="icon" type="image/png" href="~/Content/dashboard/img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>Light Bootstrap Dashboard by Creative Tim</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <!-- Bootstrap core CSS     -->
    <link href="~/Content/dashboard/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="~/Content/dashboard/css/animate.min.css" rel="stylesheet" />

    <!--  Light Bootstrap Table core CSS    -->
    <link href="~/Content/dashboard/css/light-bootstrap-dashboard.css?v=1.4.0" rel="stylesheet" />

    <!-- CK Editor JS     -->
    <script src="~/Content/ckeditor/ckeditor.js"></script>


    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="~/Content/dashboard/css/demo.css" rel="stylesheet" />
    <script src="~/Content/dashboard/js/jquery.3.2.1.min.js"></script>


    <!--     Fonts and icons     -->
    @*<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">*@
    <link href="~/Content/css/fa/css/all.css" rel="stylesheet" />
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="~/Content/dashboard/css/pe-icon-7-stroke.css" rel="stylesheet" />

</head>
<body>
    <div class="wrapper">

        <div class="sidebar" data-color="purple" data-image="http://localhost:57724/Content/dashboard/img/sidebar-2.jpg">

            <!--

                Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
                Tip 2: you can also add an image using data-image tag

            -->

            <div class="sidebar-wrapper">
                <div class="logo" style="display:flex; flex-direction:column; align-items:center">
                    <a href="http://yusufyilmaz.org" target="_blank" class="simple-text">
                        Yusuf Yılmaz
                    </a>
    @*                <img width="80" src="data:image/jpeg;base64, @imageData" style="border-radius:100%" />*@
                </div>

                <ul class="nav">

                    <li>
                        <a href="/Account/Index">
                            <i class="pe-7s-graph"></i>
                            <p>Dashboard</p>
                        </a>
                    </li>

                    <li>
                        <a href="/Account/User/">
                            <i class="pe-7s-user"></i>
                            <p>User Profile</p>
                        </a>
                    </li>
                    <li>
                        <a href="/Account/Posts/">
                            <i class="pe-7s-news-paper"></i>
                            <p>Blog(s)</p>
                        </a>
                    </li>
                    <li>
                        <a href="/Account/Categories/">
                            <i class="pe-7s-wallet"></i>
                            <p>Categorie(s)</p>
                        </a>
                    </li>

                    <li>
                        <a href="/Account/Comments">
                            <i class="pe-7s-comment"></i>
                            <p>Comment(s)</p>
                        </a>
                    </li>

                    <li>
                        <a href="/Account/SmtpSettings">
                            <i class="pe-7s-mail-open"></i>
                            <p>SMTP Settings</p>
                        </a>
                    </li>

                    <li>
                        <a href="/Account/PasswordSettings">
                            <i class="pe-7s-settings"></i>
                            <p>Password Settings</p>
                        </a>
                    </li>

                    <li>
                        <a href="/Account/General">
                            <i class="pe-7s-edit"></i>
                            <p>General</p>
                        </a>
                    </li>

                    <li>
                        <a href="javascript:void(0)">
                            <i class="pe-7s-bell"></i>
                            <p>Notifications</p>
                        </a>
                    </li>

                </ul>
            </div>
        </div>


        <div class="main-panel">

            <nav class="navbar navbar-default navbar-fixed">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#">Dashboard</a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-left">
                            <li>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-dashboard"></i>
                                    <p class="hidden-lg hidden-md">Dashboard</p>
                                </a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-globe"></i>
                                    <b class="caret hidden-sm hidden-xs"></b>
                                    <span class="notification hidden-sm hidden-xs">5</span>
                                    <p class="hidden-lg hidden-md">
                                        5 Notifications
                                        <b class="caret"></b>
                                    </p>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Notification 1</a></li>
                                    <li><a href="#">Notification 2</a></li>
                                    <li><a href="#">Notification 3</a></li>
                                    <li><a href="#">Notification 4</a></li>
                                    <li><a href="#">Another notification</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="">
                                    <i class="fa fa-search"></i>
                                    <p class="hidden-lg hidden-md">Search</p>
                                </a>
                            </li>
                        </ul>

                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="/Account/User/">
                                    <p>Account</p>
                                </a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <p>
                                        Dropdown
                                        <b class="caret"></b>
                                    </p>

                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">Separated link</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="/Account/Logout">
                                    <p>Log out</p>
                                </a>
                            </li>
                            <li class="separator hidden-lg"></li>
                        </ul>
                    </div>
                </div>
            </nav>

            <div class="content">

                @RenderBody()

            </div>

            <footer class="footer">
                <div class="container-fluid">
                    <nav class="pull-left">
                        <ul>
                            <li>
                                <a href="/" target="_blank">
                                    Home
                                </a>
                            </li>
                            <li>
                                <a href="http://yusufyilmaz.org" target="_blank">
                                    Company
                                </a>
                            </li>
                            <li>
                                <a href="/Home/Portfolio" target="_blank">
                                    Portfolio
                                </a>
                            </li>
                            <li>
                                <a href="/" target="_blank">
                                    Blog
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <p class="copyright pull-right">
                        &copy;
                        <script>document.write(new Date().getFullYear())</script>
                    </p>
                </div>
            </footer>


        </div>

    </div>



</body>


<!--   Core JS Files   -->
<script src="~/Content/dashboard/js/jquery.3.2.1.min.js" type="text/javascript"></script>

<script src="~/Content/dashboard/js/bootstrap.min.js" type="text/javascript"></script>

<!--  Charts Plugin -->
<script src="~/Content/dashboard/js/chartist.min.js"></script>

<!--  Notifications Plugin    -->
<script src="~/Content/dashboard/js/bootstrap-notify.js"></script>

<!--  Google Maps Plugin    -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

<!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
<script src="~/Content/dashboard/js/light-bootstrap-dashboard.js?v=1.4.0"></script>

<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
<script src="~/Content/dashboard/js/demo.js"></script>


<script type="text/javascript">
    $(document).ready(function () {

        demo.initChartist();

        $.notify({
            icon: 'pe-7s-gift',
            message: "Welcome to <b>Light Bootstrap Dashboard</b> - a beautiful freebie for every web developer."

        }, {
                type: 'info',
                timer: 4000
            });

    });
</script>

</html>

NetMVCBlogApp/NetMVCBlogApp/Views/Shared/header-footer.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    @Html.Action("MetaTags", "Seo", new { @value = ViewBag.Value})
    
    <link rel="shortcut icon" href="~/Content/img/icon/icon.png" />
    <link href="https://fonts.googleapis.com/css?family=K2D" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bitter" rel="stylesheet">
    <link rel="stylesheet" href="~/Content/css/style.css">
    <link rel="stylesheet" href="~/Content/css/fa/css/all.css">
    <script src="~/Content/js/jquery.js"></script>
    @RenderSection("ck_editor", false)


    <title>@ViewBag.Title</title>


</head>


<body>

    <!-- Header Start -->
    <div id="Header">

        @Html.Action("HeaderItem", "Home")

        <div class="nav">

            @Html.Action("NavbarItem", "Home")

            <div class="nav-bar">
                <ul class="nav-bar-item">
                    <li><a href="/">Home</a></li>
                    <li><a href="#">Features</a></li>
                    <li><a href="#">Portfolio</a></li>
                    <li><a href="/About-Me">About Me</a></li>
                    <li><a href="/Contact">Contact</a></li>
                </ul>
            </div>
            <div class="search">
                <form action="/Blog/Search" method="GET">
                    <div class="search-item">
                        <input class="search-text" type="text" name="q" id="q" placeholder="search something">
                        <label for="search"><i class="fal fa-search"></i></label>
                    </div>
                </form>
            </div>
            <div class="hamburger-menu">
                <div>
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->

    @RenderBody()

    <!-- Footer Start -->

    <div class="dummy" style="margin-top:50px"></div>
    <div id="Footer">
        <div class="mail-signup">
            <div class="mail-signup-text">
                <h3>
                    <span>
                        Stay Updated
                        <i class="fal fa-envelope" style="font-size: 30px;"></i>
                    </span>
                </h3>
                <p>Subscribe your e-mail address and get to know about fresh stuff!</p>
            </div>
            <div class="signup-form">
                <form name="mail-register">
                    <input required type="email" name="subscribe" id="subscribe" placeholder="Your Email Address">
                    <button id="subscribe-signup" class="subscribe-signup" type="submit">Sign up</button>
                </form>

                <script>

                    document.getElementById('subscribe-signup').addEventListener('click', function (e) {

                        let data = {
                            email: document.getElementById('subscribe').value
                        }


                        let xhttp = new XMLHttpRequest();

                        xhttp.open('POST', '/Subscriber/Add/');

                        xhttp.onload = () => {
                            if (xhttp.status == 200) {
                                if (xhttp.responseText == "yes") {
                                    alert("Success! <3");
                                }
                                else {
                                    alert("Ops!, try again later :(");
                                }
                            }
                        }

                        xhttp.setRequestHeader('Content-type', 'application/json');

                        xhttp.send(JSON.stringify(data));

                        e.preventDefault();

                    });

                </script>
            </div>
        </div>
        <div class="footer-text">
            <h4>
                <i class="fal fa-code" style="font-size: 20px; margin-right: 5px;"></i>
                Coded By <a style="color:#333; box-shadow: inset 0 -7px 0 #FFFC7F;" target="_blank" href="http://www.yusufyilmaz.org">
                    Yusuf
                    Yılmaz
                </a>
                <!-- <i class="fal fa-code" style="font-size: 20px; margin-left: 20px"></i> -->
            </h4>
        </div>
    </div>
    <!-- Footer End -->


</body>

</html>