NetMVCBlogApp/NetMVCBlogApp/Controllers/AsideController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NetMVCBlogApp.Entity;
using NetMVCBlogApp.Models;

namespace NetMVCBlogApp.Controllers
{
    public class AsideController : Controller
    {
        BlogDBEntities context = new BlogDBEntities();

        // GET: Aside

        [ChildActionOnly]
        public PartialViewResult Index()
        {
            return PartialView();
        }

        [ChildActionOnly]
        public PartialViewResult AboutMe()
        {
            AdminDetailsModel admin = context.Admin.Select(i => new AdminDetailsModel
            {
                Image = i.Image,
                Name = i.Name,
                AboutMe = i.AboutMe
            }).FirstOrDefault();

            return PartialView(admin);
        }

        [ChildActionOnly]
        public PartialViewResult CategoryList()
        {
            return PartialView(context.Category.ToList());
        }

        [ChildActionOnly]
        public PartialViewResult RecentlyPost()
        {
            return PartialView(context.Post.OrderByDescending(i => i.ID).Where(i => i.isValid).Take(6));
        }

        [ChildActionOnly]
        public PartialViewResult WrittenBy()
        {
            AdminDetailsModel admin = context.Admin.Select(i => new AdminDetailsModel
            {
                Image = i.Image,
                Name = i.Name,
                LastName = i.LastName,
                ShortDescription = i.ShortDescription,
                AboutMe = i.AboutMe
            }).FirstOrDefault();

            return PartialView(admin);
        }
       
    }
}

NetMVCBlogApp/NetMVCBlogApp/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NetMVCBlogApp.Entity;
using NetMVCBlogApp.Models;

namespace NetMVCBlogApp.Controllers
{
    public class BlogController : Controller
    {

        BlogDBEntities context;
        public string title { get; set; }

        public BlogController()
        {
            context = new BlogDBEntities();
            title = context.Options.Select(i => i.Title).FirstOrDefault();
        }

        // GET: Blog
        [Route("{blog}-{id:int}")]
        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);


            BlogDetailsModel blog = context.Post.Where(i => i.ID == id && i.isValid).Select(i => new BlogDetailsModel
            {
                ID = i.ID,
                Name = i.Name,
                Image = i.Image,
                Text = i.Text,
                addedDate = i.AddedDate,

                Comments = i.Comment.Where(k => k.isValid).Select(j => new BlogCommentModel
                {
                    CommentID = j.ID,
                    Name = j.Name,
                    Text = j.Text,
                    Image = j.Image,
                    AddedDate = j.AddedDate,

                    CommentResponses = j.CommentResponse.Where(k => k.isValid).Select(k => new BlogCommentResponseModel
                    {
                        Name = k.Name,
                        Text = k.Text,
                        Image = k.Image,
                        AddedDate = k.AddedDate

                    }).ToList()

                }).ToList(),

            }).FirstOrDefault();

            if (blog == null)
                return HttpNotFound();

            ViewBag.Title = string.Format("{0} » {1}", title, blog.Name);
            ViewBag.Value = blog.Name;

            return View(blog);

        }

        public ActionResult Search(string q)
        {
            ViewBag.Title = string.Format("{0} | Search: {1}", title, q);

            var model = context.Post.Where(i => i.Text.Contains(q) || i.Name.Contains(q)).AsQueryable();
            return View(model.Where(i => i.isValid).OrderByDescending(i => i.ID).ToList());
        }

        [Route("category-{name}")]
        public ActionResult Categorie(int? Id)
        {
            return View(context.Post.Where(i => i.CategoryID == Id && i.isValid).ToList());
        }

        public string AddComment(CommentModel model)
        {
            if (ModelState.IsValid)
            {
                context.Comment.Add(new Comment()
                {
                    PostID = model.BlogID,
                    Name = model.Name,
                    Text = model.Text,
                    Mail = model.Email,
                    AddedDate = DateTime.Now,
                    Image = "he" + new Random().Next(1, 5) + ".png"
                });

                context.SaveChanges();
                return "yes";
            }
            return "no";
        }

        public string AddCommentResponse(CommentResponseModel model)
        {
            if (ModelState.IsValid)
            {
                context.CommentResponse.Add(new CommentResponse()
                {
                    CommentID = model.CommentID,
                    Mail = model.Email,
                    Name = model.Name,
                    Text = model.Text,
                    AddedDate = DateTime.Now,
                    Image = "he" + new Random().Next(1, 5) + ".png"
                });

                context.SaveChanges();
                return "yes";
            }
            return "no";
        }

    }
}

NetMVCBlogApp/NetMVCBlogApp/Views/Aside/AboutMe.cshtml
@model NetMVCBlogApp.Models.AdminDetailsModel

<div class="about">
    <div class="about-me">
        <h2>
            <span>About Me</span>
        </h2>
    </div>
    <div class="about-me-image">
        <img src="data:image/jpeg;base64, @Convert.ToBase64String(Model.Image)" alt="@Model.Name profile image">
    </div>
    <div class="about-me-text">
        @{
            if (Model.AboutMe!=null)
            {
                if (Model.AboutMe.Length<108)
                {
                    <span>
                        @Model.AboutMe
                    </span>
                }
                else
                {
                    <span>
                        @Model.AboutMe.Substring(0,108)...
                    </span>
                }
            }
        }
        <a href="/About-Me">more</a>
    </div>
</div>

NetMVCBlogApp/NetMVCBlogApp/Views/Aside/CategoryList.cshtml
@model IEnumerable<NetMVCBlogApp.Entity.Category>

<div class="categories">
    <h2 class="categories-header">
        <span>
            Categories
        </span>
    </h2>
    <ul class="category-list">
        @foreach (var category in Model)
        {
            <li><a href="@Url.Action("Categorie","Blog",new { name = new NetMVCBlogApp.Models.CreateFriendlyUrl().GenerateSlug(category.Name), Id = category.ID})">@category.Name</a></li>
        }
    </ul>
</div>

NetMVCBlogApp/NetMVCBlogApp/Views/Aside/Index.cshtml
@{
    Layout = null;
}

<div class="aside">
    @Html.Action("AboutMe", "Aside")
    @Html.Action("CategoryList", "Aside")
    @Html.Action("RecentlyPost", "Aside")
</div>

NetMVCBlogApp/NetMVCBlogApp/Views/Aside/RecentlyPost.cshtml
@model IEnumerable<NetMVCBlogApp.Entity.Post>

<div class="recent-posts">
    <h2 class="recent-posts-header">
        <span>
            Recent Posts
        </span>
    </h2>
    <ul class="category-list">
        @foreach (var recently in Model)
        {
            <li><a href="@Url.Action("Details","Blog", new { blog=recently.SeoLink, id=recently.ID })">@recently.Name</a></li>
        }
    </ul>
</div>

NetMVCBlogApp/NetMVCBlogApp/Views/Aside/WrittenBy.cshtml
@model NetMVCBlogApp.Models.AdminDetailsModel

<div class="author">
    <div class="author-title">
        <h6>
            <span style="box-shadow: inset 0 -7px 0 #FFFC7F;">WRITTEN BY</span>
        </h6>
    </div>
    <div class="author-info">
        <div class="author-image">
            <img src="data:image/jpg;base64, @Convert.ToBase64String(Model.Image)" alt="@Model.Name @Model.LastName">
        </div>
        <div class="author-description">
            <h6>
                <span style="font-weight: bold">@Model.Name @Model.LastName</span>
            </h6>
            <p>
               @Model.ShortDescription
            </p>
        </div>
    </div>
</div>